### PR TITLE
79 implement find in page

### PR DESCRIPTION
**Pull request by BPerlakiH**
Fixes: #79 

## iPhone:

https://github.com/kiwix/kiwix-apple/assets/6784320/f83a6201-bc79-4ea7-aa1f-e54f0ed5c53b

## iPad:

https://github.com/kiwix/kiwix-apple/assets/6784320/0369c904-3253-4413-a954-617ad1532981

## macOS: 

https://github.com/kiwix/kiwix-apple/assets/6784320/f7d6ce3b-2025-4b03-ae99-55926af5d6a6

### CODE REVIEW

**Comment by kelson42** [comment]
@BPerlakiH To me looks good, but actually I can not figure out where do you exactly click to raise this "find in page" feature?!

**Comment by BPerlakiH** [comment]
@kelson42 I had to do a couple implementations, to adjust to each device:
- on iOS I had to add a new icon in the top bar (the one on the right):
Screenshot 2024-07-10 at 11 55 03

and on iPad (full screen mode) it's a new icon (left to the "home" icon):


whereas on macOS it's a floating button in the bottom right corner:
Screenshot 2024-07-10 at 11 57 16
or you can press "CMD+F" to bring it up.

**Comment by kelson42** [comment]
@BPerlakiH Thank you for the clarification. Two remarks:
* For iPhone, I believe this feature is not proeminent enough to have its own logo. Any chance to make it available through two clicks somewhere? Idependently of this, I don't understand why we have so much space between icons?! Is that some kind of iOS/usability rule?
* For iPadOS, basically same remark as for iPhone, but far less problematic as we have a lot of space
* For macOS, the logo is not OK: far too small and not centered properly

**Comment by BPerlakiH** [comment]
I think double tab/click might conflict with other actions reserved for that, like selecting / copying text and such within the web "area". If we do a long tap, or something more alternate it won't be found by users. By looking into our app reviews, most complaints we had regarding this behaviour for the catalog / settings icon (where you had to long press to bring it up).

The spacing is the default OS spacing for tab navigation items, so this is the accepted default by Apple for accessibility.

**Comment by kelson42** [comment]
@BPerlakiH With two clicks, I don't mean a double click, I mean somewhere through a menu.

**Comment by kelson42** [comment]
I will merge and UI improvement should be handled in separate issue

**Review by kelson42 — APPROVED** [review]
LGTM

**Comment by VitoVan** [comment]
Waiting for the new release with excitement...

🎉 🎉 🎉

**Pull request merged**
