### PR TITLE
Fix bookmarking of PDFs

### PR DESCRIPTION
**Pull request by BPerlakiH**
Fixes: #817 

Currently this is how it looks with all the Water docs bookmarked on macOS:

Screenshot 2024-06-22 at 14 25 39

### CODE REVIEW

**Comment by kelson42** [comment]
@BPerlakiH You should not need a PDF parser if you don't need an HTML parser. This is also not what os requested in the issue. I really don't get it.

**Comment by BPerlakiH** [comment]
@kelson42 The bookmarks are currently containing these fields we do display:
- title 
- (optional) short snippet
- (optional) image url

So far we were getting these fields only via an HTML parser. In case of a PDF file it was not working as expected. Therefore I thought we might use a PDF parser to get the same fields if possible.

**Comment by BPerlakiH** [comment]
In case of a non html (text) document, I can simplify it to be:
- title replaced with the path
- no snippet
- no image

**Comment by kelson42** [comment]
@BPerlakiH Indeed, but not sure what you mean?

**Comment by kelson42** [comment]
yes, this is what is requested in the issue and this is appropriate to me.

So, as far as I understand you wanted to get a better bookmark by allowing to get a better bookmark. Can you please:
* open a dedicated issue to explain the problem and proposal
* move the appropriate code in a draft PR

**Comment by benoit74** [comment]
As discussed for nautilus and zimit, I think it makes much more sense to enhance scrapers so that they populate properly the title and provide proper indexing data for search. This would allow all readers to benefit from such an enhancement at once. I don't mind if this is implement in apple reader, but it might soon be "obsolete" once all pdfs have a proper title due to implementation in the scraper. I intend to add this to the python-scraperlib in the coming weeks.

**Comment by kelson42** [comment]
@benoit74 At the core of this issue is a lack of PDF support at scraper size. But, even if this has to be fixed there, it has to be handled properly at reader level if not title metadat. For PDF or any other supported mime-type.

**Comment by BPerlakiH** [comment]
I've updated this PR, and created a new issue for the more detailed solution: https://github.com/kiwix/kiwix-apple/issues/827

**Review by kelson42 — APPROVED** [review]

**Comment by rgaudin** [comment]
I'm a bit worried by this PR. I feel there's no room for discussion and everything is rushed.

My first opinion when reading the PR description was the one of @kelson42 but reading the implementation, I think it was the appropriate way to go: PDF is a natively supported format on apple system. Hence the PDF Parser is builtin.
The PR had the appropriate fallback so ZIM entry so it was respecting the same concept as for HTML: if document itself has a title, use it (as in a regular browser or pdf reader) and if not fallback to ZIM.

**Comment by kelson42** [comment]
@rgaudin See [my comment](https://github.com/kiwix/kiwix-apple/issues/827#issuecomment-2184074829) to the dedicated ticket.

**Pull request merged**
