### PR TITLE
Fix favIcons of opened ZIM files (not added via catalog download)

### PR DESCRIPTION
**Pull request by BPerlakiH**
Fixes: #789

### CODE REVIEW

**Comment by kelson42** [comment]
@BPerlakiH CI does not pass

**Comment by kelson42** [comment]
@BPerlakiH What isnthenlogic of usage between the remote URL and the local illustration?

**Comment by BPerlakiH** [comment]
@kelson42 I have updated the code, it seems that empty string to empty data was not handled properly.
What isnthenlogic of usage between the remote URL and the local illustration?

**Comment by kelson42** [comment]
AFAP usenonline catalogue metadata (even in local library) and otherwise the local (from ZIM file).

**Comment by BPerlakiH** [comment]
If the url is set, that will be displayed, if not it will fallback to the image data, so that covers the scenario you mentioned.

**Pull request merged**
