### PR TITLE
Change "mailto:" urls to be external

### PR DESCRIPTION
**Pull request by BPerlakiH**
Fixes: #780

### CODE REVIEW

**Comment by kelson42** [comment]
@BPerlakiH Is that the right logic!? Everything which is not zim:// should be external IMHO.

**Comment by BPerlakiH** [comment]
> @BPerlakiH Is that the right logic!? Everything which is not zim:// should be external IMHO.
> 
> We have a few other schemes, for example, tel: geo: ftp:...

I did found that we handle "geo" scheme separately. Should we say that everything apart from "kiwix" and "geo" is external then ?

**Comment by BPerlakiH** [comment]
@kelson42 Please see it updated.

**Comment by kelson42** [comment]
@BPerlakiH This looks more what I was expacted. From a user perspective, its important the OS tries to open the link with the appropriate app, in the case of mailto: the default mail app.

Here a few remarks which are related to the naming of things:
* We should have a zim:// protocol, not a kiwix:// protocol, can we change that in a dedicated issue/PR?
* I challenge the "external" naming, probably "unsupported" would be better?

**Pull request merged**
